# Generated by Django 3.2.9 on 2021-11-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('rut_usuario', models.CharField(max_length=8, verbose_name='rut usuario')),
                ('primer_nombre', models.CharField(blank=True, max_length=50, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre')),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=50, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=1, verbose_name='Género')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección de residencia')),
                ('email', models.CharField(max_length=6, verbose_name='Dirección de correo electrónico')),
                ('telefono', models.CharField(max_length=6, verbose_name='Teléfono')),
            ],
        ),
    ]
