# Generated by Django 3.2.9 on 2021-11-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='rut_usuario',
            new_name='rut_paciente',
        ),
    ]
