# Generated by Django 3.2.9 on 2021-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_rut_usuario_paciente_rut_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='contrasena',
            field=models.CharField(default=1234, max_length=10, verbose_name='Constraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='contrasena2',
            field=models.CharField(default=1234, max_length=10, verbose_name='Repetir contraseña'),
            preserve_default=False,
        ),
    ]
