# Generated by Django 3.2.9 on 2021-11-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211124_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.CharField(max_length=6, null=True, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut_paciente',
            field=models.CharField(max_length=8, null=True, primary_key=True, serialize=False, verbose_name='rut usuario'),
        ),
    ]
