# Generated by Django 3.2.9 on 2021-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211124_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut_paciente',
            field=models.CharField(max_length=10, null=True, primary_key=True, serialize=False, verbose_name='rut usuario'),
        ),
    ]
