# Generated by Django 3.2.9 on 2021-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_paciente_rut_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Dirección de correo electrónico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='Teléfono'),
        ),
    ]
